image: gitpod/workspace-full
tasks:
  - name: Setup
    before: |
      sudo apt-get -y update
      sudo apt-get -y upgrade
      sudo apt-get -y install language-pack-ja graphviz fonts-noto* language-selector-common
      sudo update-locale LANG=ja_JP.UTF8
      echo 'export LANG=ja_JP.UTF-8' >> ~/.bashrc
      export LANG=ja_JP.UTF-8
      fc-cache -f
      fc-match sans-serif
vscode:
  extensions:
    - asciidoctor.asciidoctor-vscode
    - EditorConfig.EditorConfig
    - mushan.vscode-paste-image
    - anwar.papyrus-pdf
    - jebbs.plantuml
