' https://github.com/iconic/open-iconic/
' ⓿❶❷❸❹❺❻❼❽❾❿⓫⓬⓭⓮⓯⓰⓱⓲⓳⓴
@startsalt directory-structure-3
{
{T
 + <&folder> src
 ++ <&folder> docs
 +++ <&folder> asciidoc
 ++++ <&folder> @style
 +++++ <&file> asciidoctor.css              | ❸
 +++++ <&file> pdf-theme.yml                | ❹
 ++++ <&folder> @font
 +++++ <&folder> genshin
 ++++++ <&file> GenShinGothic-Regular.ttf   | ❺
 ++++++ <&file> ..snip..
 +++++ <&folder> genyo-font
 +++++ <&folder> ..snip..
 ++++ <&folder> Chapter00                   | ❻
 +++++ <&file> index.adoc
 ++++ <&folder> Chapter01
 +++++ <&folder> images
 +++++ <&file> index.adoc
 ++++ <&folder> ..snip..
 ++++ <&file> attribute.adoc                | ❷
 ++++ <&file> index.adoc                    | ❶
 + <&file> build.gradle                     | ❼
}
}
@endsalt
