include::../attribute.adoc[]

[[project-structure]]
== Asciidoc 記法

=== 文書中の相互参照

文書内の参照リンクは ``.adoc`` 文書中で次のように指定します。HTML/PDF でクリックリンクが生成されます。

[source]
----
[[project-structure]] // <1>
== Asciidoc 記法

[[introduction]] // <2>
== はじめに

<<project-structure,章の冒頭>> // <1>
<<Chapter01/index.adoc#introduction,はじめに>> <2>
----

<1> 同一 `.adoc` 内での内部参照
<2> `.adoc` をまたいだドキュメント間参照

リンクの例

* <<project-structure,章の冒頭>> を参照してください･･･
* <<Chapter01/index.adoc#introduction,はじめに>> で述べたように･･･

=== ソースコードシンタックスハイライト

``[sorce]`` ブロックを用いて文書中にソースコードをシンタックスハイライト付きで埋め込みます。また、``// <1>`` 形式でソースコード下部に対応する説明が書けます。

[source]
-----
[source, javascript]
[caption=""]
.JavaScript ソースコードのシンタックスハイライトの例
----
function hello() {
    console.log("Hello, World!"); // \<1>
}
----

<1> コンソールに ``Hello, World`` を出力
-----

[source, javascript]
[caption=""]
.JavaScript ソースコードのシンタックスハイライトの例
----
function hello() {
    console.log("Hello, World!"); // <1>
}
----

<1> コンソールに ``Hello, World`` を出力

=== ファイルインクルード

`.adoc` ファイルから別のファイルをインクルードできます。ソースコードや後述のダイアグラム形式などを別ファイルとして切り出すのに便利です。

IMPORTANT: Gradle のファイル更新監視は `.adoc` からインクルードされたファイルまでは及びません。インクルード先のファイルだけを書き換えた場合は `./gradlew docs` が処理なしで終了してしまいますので、この場合は `./gradlew clean` するなどしてからリビルドしてください。

[source]
-----
[source, rust]
----
\include::source/hello.rs[]
----
-----

[source, rust]
[caption=""]
.インクルードにより挿入されたソースコードの例
----
include::source/hello.rs[]
----

=== 表形式

表形式は次のようなコードで定義することができます。

[source]
-----
[format="csv",cols="1,2"]
[frame="topbot",grid="none"]
[caption=""]
.表形式の例
|======
カラム1,カラム2
キー1,バリュー1
キー2,バリュー2
|======
-----

[format="csv",cols="1,2"]
[frame="topbot",grid="none"]
[caption=""]
.表形式の例
|======
カラム1,カラム2
キー1,バリュー1
キー2,バリュー2
|======

=== 脚注

補足点を脚注するいくつかの表現があります。

[source]
-----
NOTE: メモ

TIP: チップス

IMPORTANT: 重要

WARNING: 警告

CAUTION: 注意
-----

NOTE: メモ

TIP: チップス

IMPORTANT: 重要

WARNING: 警告

CAUTION: 注意


=== コラム表現

[source]
-----
.コラム
****
ブロックを使ってコラム表現を挿入します。

吾輩はコラムである。名前はまだ無い。
****
-----

.コラム
****
ブロックを使ってコラム表現を挿入します。

吾輩はコラムである。名前はまだ無い。
****

<<<<

=== ダイアグラム記法

本変換ビルドスクリプトでは `asciidoctorj-diagram` が有効になっており、いくつかのダイアグラム記法を追加のアドイン無しで使うことができます。

==== PlantUML

記事中に PlantUML 形式のダイアグラムを記述し、生成された `.svg` ベクター画像を文書に展開するには次のようにします。

===== シーケンス図の例

[source]
-----
[plantuml, diag-sequence-sample2, svg, pdfwidth=70%, width=70%]
[caption=""]
----
include::puml/diag-sequence-sample2.puml[]
----
-----

[plantuml, diag-sequence-sample2, svg, pdfwidth=70%, width=70%]
[caption=""]
----
include::puml/diag-sequence-sample2.puml[]
----

.PlantUML ダイアグラムのリアルタイムプレビュー編集
****
本手順の VS Code の推奨プラグインとなっている PlantUML 拡張（``jebbs.plantuml``）を使うと、PlantUML のダイアグラム記法も VS Code 上でリアルタイムプレビューすることができます。

プレビュー処理をするために必要な PlantUML サーバは Docker コンテナで起動すると便利でしょう。なお、Gradle による文書の変換では内蔵の PlantUML ライブラリが使われますので本サーバーが起動している必要はありません。

[source, bash]
----
docker run -d --rm -p 8080:8080 plantuml/plantuml-server:jetty
----

`.vscode/setting.json` は次のようにポート ``8080`` で PlantUML サーバが起動されることを期待して構成してあります。

[source, json]
[caption=""]
.`.vscode/setting.json`
----
{ "plantuml.server": "http://localhost:8080" }
----

文書で使う PlantUML ダイアグラムを `.puml` 拡張子で保存することで Asciidoc と同様にプレビューアイコンが表示され、プレビュー画面ではリアルタイムに `.puml` ファイルの修正が反映されます。
****

<<<<

===== Salt の例(1)

[source]
-----
[plantuml, diag-salt-sample1, svg, pdfwidth=30%, width=280px]
[caption=""]
----
include::puml/diag-salt-sample1.puml[]
----
-----

[plantuml, diag-salt-sample1, svg, pdfwidth=30%, width=280px]
[caption=""]
----
include::puml/diag-salt-sample1.puml[]
----

===== Salt の例(2)

[source]
-----
[plantuml, diag-salt-sample2, svg, pdfwidth=30%, width=30%]
[caption=""]
----
include::puml/diag-salt-sample2.puml[]
----
-----

[plantuml, diag-salt-sample2, svg, pdfwidth=30%, width=30%]
[caption=""]
----
include::puml/diag-salt-sample2.puml[]
----

===== AsciiMath の例

[source]
-----
[plantuml, math-sample1, svg, pdfwidth=70%, width=70%]
[caption=""]
----
include::puml/math-sample1.puml[]
----
-----

[plantuml, math-sample1, svg, pdfwidth=70%, width=70%]
[caption=""]
----
include::puml/math-sample1.puml[]
----
