include::../attribute.adoc[]

== Gradle ビルドの詳細

本項では、これまで使ってきた ``docs`` や ``clean`` のような Gradle タスクの詳細を解説します。この内容は執筆に直接影響しませんが、予備知識として知ることでプロジェクトフォルダ構成変更などビルドのカスタマイズが行えます。

また合わせて、ここまで登場しなかった執筆中に有用と思われるユーティリティタスクについても示します。

本項で解説する Gradle タスクは次のとおりです。

[cols="1,2"]
[frame="topbot", grid="none", options="header"]
[caption=""]
.Gradle タスク一覧
|======
|タスク名
|役割
|``tasks``
|``build.gradle`` で定義された全てのタスク名と説明を出力します。

|``docs``
|``src/docs/asciidoc/index.adoc`` の Asciidoc 文書を HTML/PDF 文書に変換し ``docs`` フォルダに格納します。

|``clean``
|``build`` フォルダ配下のファイルを削除しビルドを初期化します。 +
include 先ファイルの更新や PDF テーマの修正など、``.adoc`` 自体に変更がない場合に本タスクを実行後、再ビルドすると結果が反映されます。

|``cleanDocs``
|``docs`` フォルダ配下のファイルを全て削除します。 +
``docs`` タスクの前提依存となっているため、このタスクを直接実行する機会はほとんどありませんが、ビルドスクリプトのカスタマイズを行う場合に使えるかもしれません。

|``checkPdfInfo``
|追加のユーティリティタスクです。 +
``docs/index.pdf`` 文書から PDF ファイルに設定されたメタ情報を出力します。このタスクは PDF 文書に誤った情報が混入していないかの確認に使えます。

|``checkSyncImage``
|追加のユーティリティタスクです。 +
``src/docs/asciidoc`` 内にある画像ファイルと Asciidoc 文書からリンクされている画像リソースを比較し、リンクされていない画像やリンク切れファイルを出力します。このタスクは過去に使われ必要なくなった画像ファイルを検出するのに便利です。
|======

=== Gradle タスクの実行方法

各々のタスクは ``build.gradle`` ファイルで定義され、``gradlew`` シェルスクリプト（Windows では ``gradlew.bat``）からタスク名を指定することで処理が実行されます。

[source, bash]
[caption="手順. "]
.Gradle タスクの実行（macOS / Linux）
----
./gradlew docs # <1>
----
<1> ``docs`` 部分がタスク名。

[source, powershell]
[caption="手順. "]
.Gradle タスクの実行（Windows）
----
.\gradlew docs # <1>
----
<1> ``docs`` 部分がタスク名。 ``gradlew`` 部分は拡張子省略形で、実際に動作しているのは ``gradlew.bat`` ファイルとなる。

TIP: Windows PowerShell 環境では、パスの区切り文字を ``\`` ではなく、macOS や Linux と同様に ``/`` としても正しく動作します。そこで、ここからの解説では環境による操作の差異を省くため、パス区切りを ``/`` に表記として示します。また、各ユーティリティタスクが出力するパスも ``/`` 形式に統一されています。

=== ``tasks`` タスク

Gradle が持つ全てのタスクは ``tasks`` タスクにより一覧表示できます。

文書のビルドで使われるタスクは ``Documentation tasks`` グループに纏まって出力されます。本タスクは詳細なタスク名を忘れた場合に使うと便利です。

[source,bash]
[caption="手順. "]
.``gradlew tasks`` の実行
----
$ ./gradlew tasks
..snip..
Documentation tasks
-------------------
asciidoctor - Generic task to convert AsciiDoc files and copy related resources
asciidoctorPdf - Convert AsciiDoc files to PDF format
checkPdfInfo - Utility task to check PDF document metadata
checkSyncImage - Utility to check the consistency of Asciidoc text and file system images
cleanDocs - Task to delete all files and directories under docs/
docs - Generate HTML/PDF documents from Asciidoc documents and output them under docs/
..snip..
----

=== ``docs`` タスク

``src/docs/asciidoc`` 配下の Asciidoc 文書を HTML/PDF 文書に変換し ``docs`` フォルダに配置するタスクです。

[source, bash]
[caption="手順. "]
.``docs`` タスク
----
./gradlew docs
----

実際の動作としては Asciidoctor Gradle Plugin の ``asciidoctor`` 及び ``asciidoctorPdf`` タスクが文書変換処理を担います。

``asciidoctor`` 及び ``asciidoctorPdf`` タスクの定義は次のとおりです。

[source, groovy]
[caption=""]
.``build.gradle`` の ``asciidoctor`` タスク定義
----
asciidoctor {
    dependsOn asciidoctorGemsPrepare // <1>
    baseDir file('src/docs/asciidoc') // <2>
    sources {
        include 'index.adoc' // <3>
    }
    resources {
        from('src/docs/asciidoc') {
            include 'Chapter*/images/*' // <4>
        }
    }
    asciidoctorj {
        attributes 'stylesdir': '@style',
            'stylesheet': 'asciidoctor.css' // <5>
    }
}
----
<1> 追加の Ruby スクリプトを最初にロードします。
<2> Asciidoc 文書の起点フォルダです。
<3> Asciidoc 文書の起点ファイルです。
<4> 画像リソース定義です。
<5> HTML 文書用のスタイル CSS 定義です。

[source, groovy]
[caption=""]
.``build.gradle`` の ``asciidoctorPdf`` タスク定義
----
asciidoctorPdf {
    dependsOn asciidoctorGemsPrepare // <1>
    baseDir file('src/docs/asciidoc') // <2>
    fontsDir file('src/docs/asciidoc/@font') // <3>
    sources {
        include 'index.adoc' // <4>
    }
    asciidoctorj {
        attributes 'pdf-themesdir': "@style",
            'pdf-theme': 'pdf-theme.yml' // <5>
    }
}
----
<1> 追加の Ruby スクリプトを最初にロードします。
<2> Asciidoc 文書の起点フォルダです。
<3> PDF 文書用のフォントフォルダ定義です。
<4> Asciidoc 文書の起点ファイルです。
<5> PDF 文書のテーマ定義です。

NOTE: ``asciidoctor`` 及び ``asciidoctorPdf`` タスクの実行結果出力先は、プロジェクトフォルダ下の ``build`` テンポラリーフォルダです。なお、ビルドを初期化する ``clean`` タスクの実態は ``build`` フォルダ内のファイルを削除する処理になっています。

また ``asciidoctorj`` 定義では、文書変換スクリプトで使われる AsciidoctorJ や周辺モジュールのバージョン設定をしています。

[source, groovy]
[caption=""]
.``build.gradle`` の ``asciidoctorj`` 定義
----
asciidoctorj {
    version = '2.5.6' // <1>
    modules {
        diagram.use()
        diagram.version '2.2.8' // <2>
        pdf.version '1.6.2' // <3>
    }
    requires = [ // <4>
        'asciidoctor-diagram',
        'prawn_svg_font_patch', // <5>
        'asciidoctor/nabetani', // <6>
    ]
    attributes 'source-highlighter': 'rouge' // <7>
}

----
<1> AsciidoctorJ のバージョン指定します。最新バージョンを指定できますが、破壊的変更がある場合にビルドが失敗する場合があるので、既存の文書のビルドでバージョンを上げる際には注意します。
<2> ダイアログ記法を処理する asciidoctor-diagram のバージョン指定です。最新バージョンが指定できます。こちらも既存文書でバージョンを上げる場合は、破壊的変更に注意します。
<3> PDF 文書変換をする asciidoctor-pdf のバージョン指定です。日本語禁則処理が ``1.6.2`` に依存しているため本ビルドでは固定です。
<4> Asciidoctor が使う Ruby スクリプトの定義です。追加のスクリプトがある場合は ``build.gradle`` ファイル上部の ``dependencies`` 部分で定義し ``gradle/repos/gem`` 配下に Ruby Gem として配置します。
<5> ダイアログ記法で使われるフォントを日本語にパッチするスクリプトです。
<6> PDF 文書で日本語禁則処理を行う asciidoctor-nabetani の導入定義です。asciidoctor-pdf ``1.6.2`` に依存します。

[TIP]
====
Asciidoc 文書変換で追加の処理が必要な場合は、Asciidoc カスタムコンバータを作成し Ruby Gem 形式でプロジェクトフォルダに配置しビルドに組み込んで実行できます。カスタムコンバータの詳細については以下のドキュメントを参照してください。

[quote, Custom Converter | Asciidoctor Docs]
____
https://docs.asciidoctor.org/asciidoctor/latest/convert/custom/

Asciidoctor supports custom converters. If you want to produce an output format that’s not supported by a built-in converter or any of the available converters in the ecosystem, you can create and use your own converter.
____
====

起動タスクとなっている ``docs`` タスクでは、ここまでで解説した Asciidoctor Gradle Plugin が事前実行依存として設定してあり、文書変換処理完了後に ``build`` フォルダに生成された文書及びリソースを ``docs`` フォルダにコピーします。

[source, groovy]
[caption=""]
.``build.gradle`` の ``docs`` タスク定義
----
tasks.register('docs', Copy) {
    dependsOn(asciidoctor, asciidoctorPdf, cleanDocs)
    group 'documentation'
    description 'Generate HTML/PDF documents from Asciidoc documents and output them under docs/'
    from 'build/docs/asciidoc/index.html' // <1>
    from 'build/docs/asciidocPdf/index.pdf' // <1>
    from('build/docs/asciidoc/') { // <2>
        include 'Chapter*/images/*'
    }
    into 'docs/'
}
----
<1> build に生成された PDF/HML 文書を docs にコピーします。
<2> HTML 文書用に build に出力された画像、ダイアログ記法で生成された SVG、表紙裏表紙カバー PDF を含む、各 images 配下の全ての画像リソースを docs にコピーします。

また、``docs`` の依存にひとつとなっている ``cleanDocs`` タスクでは ``docs`` フォルダのクリーンアップを行っています。

[source, groovy]
[caption=""]
.``build.gradle`` の ``cleanDocs`` タスク定義
----
tasks.register('cleanDocs', Delete) {
    group 'documentation'
    description 'Task to delete all files and directories under docs/'
    // docs/ ディレクトリは残しその配下のファイルとディレクトリを全て削除
    delete file('docs/').listFiles()
}
----

TIP: 本項で現れたビルドスクリプト中に現れるパスを変更することで、プロジェクトフォルダのファイル・フォルダ構成を変更できます。

=== ``checkPdfInfo`` タスク

``checkPdfInfo`` タスクは ``docs/index.pdf`` に生成された PDF のメタ情報を出力します。

[source, bash]
[caption="手順. "]
.``checkPdfInfo`` タスクの実行
----
./gradlew -q checkPdfInfo
----

TIP: ``gradlew`` の -q`` オプションは Gradle からのビルドメッセージ出力を抑止し、タスクからの出力を見やすくするオプションです。

このタスクの出力結果は次のようになります。

[source, bash]
[caption="手順. "]
.``checkPdfInfo`` タスクの出力例
----
Content-Type: application/pdf
access_permission:assemble_document: true
access_permission:can_modify: true
access_permission:can_print: true
access_permission:can_print_degraded: true
access_permission:extract_content: true
access_permission:extract_for_accessibility: true
access_permission:fill_in_form: true
access_permission:modify_annotations: true
dc:creator: https://github.com/h1romas4/asciidoctor-gradle-template
dc:format: application/pdf; version=1.4
dc:title: AsciidoctorとGradleでつくる文書執筆環境
dcterms:created: 2023-10-04T06:17:20Z
dcterms:modified: 2023-09-25T08:40:46Z
pdf:PDFVersion: 1.4
pdf:annotationSubtypes: Link
pdf:annotationTypes: null
pdf:charsPerPage: 0
pdf:containsDamagedFont: false
pdf:containsNonEmbeddedFont: false
pdf:docinfo:created: 2023-10-04T06:17:20Z
pdf:docinfo:creator: https://github.com/h1romas4/asciidoctor-gradle-template
pdf:docinfo:creator_tool: Asciidoctor PDF 1.6.2, based on Prawn 2.4.0
pdf:docinfo:modified: 2023-09-25T08:40:46Z
pdf:docinfo:producer: https://github.com/h1romas4/asciidoctor-gradle-template
pdf:docinfo:title: AsciidoctorとGradleでつくる文書執筆環境
pdf:encrypted: false
pdf:hasCollection: false
pdf:hasMarkedContent: false
pdf:hasXFA: false
pdf:hasXMP: false
pdf:num3DAnnotations: 0
pdf:overallPercentageUnmappedUnicodeChars: 0.0
pdf:producer: https://github.com/h1romas4/asciidoctor-gradle-template
pdf:totalUnmappedUnicodeChars: 0
pdf:unmappedUnicodeCharsPerPage: 0
xmp:CreatorTool: Asciidoctor PDF 1.6.2, based on Prawn 2.4.0
xmpTPg:NPages: 77
----

PDF 文書のメタ情報には、主に ``src/docs/asciidoc/index.adoc`` で設定したタイトルや著者名などが記録されますが、本タスクで正しく設定されているかを確認できます。

=== ``checkSyncImage`` タスク

``checkSyncImage`` タスクは、Asciidoc 文書から使われている画像リソースと ``src/docs/asciidoc`` 内のファイルを比較し一致性を出力します。特に未使用画像を検出するのに便利なタスクです。

[source, bash]
[caption="手順. "]
.``checkSyncImage`` タスクの実行
----
./gradlew -q checkSyncImage
----

このタスクの出力結果は次のようになります。

[source, bash]
[caption="手順. "]
.``checkPdfInfo`` タスクの出力例
----
::Unused images:
Chapter01/images/unused-image-1.png
Chapter03/images/unused-image-1.png
::Image not found:
Chapter01/images/2023-09-17-13-43-06.png
----

それぞれの出力項目の内容は次のとおりです。なお、タスクの実行で何も出力されず正常終了した場合は、Asciidoc 文書と画像ファイルが整合していることを示します。

``::Unused images:``::
    Asciidoc 文書からリンクされていない未使用画像ファイルの一覧です。これらは不要なファイルとして削除できます。
``::Image not found:``::
    Asciidoc 文書からリンクされているが存在しない画像ファイルの一覧です。画像リンク切れファイルはビルド時の ``docs`` タスクでも警告となり、文書を修正する必要があります。

TIP: ``::Unused images:`` に申告されたファイルは未使用ながら ``docs`` 配下の HTML 文書用画像フォルダに転送されます。HTML 文書の配布を行う場合は、本タスクで検出して ``src/docs/asciidoc`` フォルダから削除後、再度文書のビルドをしてクリーンアップすると良いでしょう。

本タスクの設定は、``build.gradle`` の次の記述で行われています。

[source, groovy]
[caption=""]
.``build.gradle`` の ``checkSyncImage`` タスク定義
----
tasks.register('checkSyncImage', SyncImageTask) {
    group 'documentation'
    description 'Utility to check the consistency of Asciidoc text and file system images'
    // 起点の文書ディレクトリ
    baseDir = file('src/docs/asciidoc')
    // 起点の Asciidoc 文書（include を辿る）
    index = 'index.adoc'
    // ファイルシステム上で画像として認識する拡張子
    // 文書内で image:: として使われているファイル全ての拡張子を設定すること
    imageExt = ['png', 'jpg', 'jpeg', 'svg']
}
----

画像ファイルは ``imageExt`` 変数で設定された拡張子をもって識別しています。

もし設定されている以外の画像拡張子が Asciidoc 文書で使われている場合は、``::Image not found:`` としてリンク切れで認識されます。必要に応じて設定を修正してください。
