include::../attribute.adoc[]

[[introduction]]
[preface]
== はじめに

本文書は **Asciidoc** とその Ruby による実装である **Asciidoctor** を用いて Asciidoc 文書を執筆する環境を構築するガイドです。実行環境は Windows、Linux、macOS の各 OS に対応しています。

この文書の手順から次のことができるようになります。

Asciidoc 形式で執筆した文書を HTML/PDF 形式に変換::
    Asciidoc 文書変換用 Gradle スクリプト
テキストエディターで変換結果をリアルタイムにプレビューしながら文書を編集::
    Visual Studio Code と AsciiDoc 拡張設定

Asciidoc は表現力の高い文書をテキストファイルベースで執筆できるテキストプロセッサーです。他の軽量テキストプロセッサーが持たない文書間のインクルードやソースコードの挿入などの機能も有し、かつ簡潔です。特に技術文書の執筆には大きな力を発揮することでしょう。

[TIP]
====
Asciidoc の表現力を示すひとつの例は、このような脚注表現です。
====

一般的にテキストプロセッサーを用いた執筆環境を整えるには多くの準備が必要ですが、本文書の手順は極力初期導入するプロダクトを少なく、簡単に快適な執筆環境を整えられるよう考えられました。

具体的には文書の変換に、実行を JVM 環境だけに依存する **AsciidoctorJ** と **Gradle** を活用し、執筆環境については **Visual Studio Code** を用いることでリアルタイムに文書をプレビューしながら、最後にコマンド一つで HTML/PDF 化できるように準備しました。またさらに、クラウド統合環境である Gitpod や GitHub の Codespaces もサポートし、ウェブブラウザだけでの執筆・変換も実現しています。

手間がかかることが多い PDF 出力に関しても、フォントセットや禁則処理設定をプロジェクトに持たせることにより、実行環境に関わらず同一出力が得られるように調整しました。

Asciidoc による文書の執筆は形式的で効率が良く、また更新差分が取りやすいため、文書履歴管理や共同執筆環境としても有効です。このメリットをさらに活用するため、本手順ではテキストダイアグラム記法による図形や数式のベクター画像挿入をサポートしています。

本文書がみなさんの執筆活動のお手伝いになれば幸いです。

<<<

=== ライセンス

本文書に含まれる筆者が作成したビルドスクリプト、サンプル文書 ``.adoc``、ダイアグラムのなどのソースは全て **MIT License** です。ライセンスに従って自由にご利用ください。

リポジトリのソースやライセンスファイルは次から参照できます。

[quote, https://github.com/h1romas4]
____
https://github.com/h1romas4/asciidoctor-gradle-template

AsciidoctorとGradleでつくる文書執筆環境
____

[NOTE]
====
https://h1romas4.github.io/asciidoctor-gradle-template/index.pdf[本文書の PDF 版の表紙]は https://github.com/Fujix1/[@Fujix さん] によって作成されました。

素敵なデザインをありがとうございました。
====

=== 謝辞

本文書の実装であるビルドスクリプトやテーマでは次のプロダクトと技術資料が使われています。

プロダクト名の隣にライセンスを併記しました。商用利用等で制限のあるプロダクトはありませんが、それぞれライセンスを確認してください。

Font::
    * 源真ゴシック - SIL Open Font License 1.1  - http://jikasei.me/font/genshin/
    * 源様明朝 - SIL Open Font License 1.1 - https://github.com/ButTaiwan/genyo-font
    * Ricty Diminished - SIL Open Font License 1.1 - https://github.com/edihbrandon/RictyDiminished
    * Morisawa BIZ UDGothic - SIL Open Font License 1.1 - https://github.com/googlefonts/morisawa-biz-ud-gothic
    * Morisawa BIZ UDMincho  - SIL Open Font License 1.1 - https://github.com/googlefonts/morisawa-biz-ud-mincho
    * Open Iconic - MIT License - https://github.com/iconic/open-iconic/
Asciidoc::
    * Asciidoctor - MIT License - https://asciidoctor.org/
    * Asciidoctorj - Apache License 2.0 - https://github.com/asciidoctor/asciidoctorj
    * Asciidoctor.js - MIT License - https://asciidoctor.org/docs/asciidoctor.js/
    * Asciidoctor PDF - MIT License - https://asciidoctor.org/docs/asciidoctor-pdf/
    * Asciidoctor Gradle Plugin Suite - Apache License 2.0 - https://github.com/asciidoctor/asciidoctor-gradle-plugin
    * asciidoctor-pdf-linewrap-ja - MIT License - https://github.com/fuka/asciidoctor-pdf-linewrap-ja
    * asciidoctor-nabetani - MIT License - https://github.com/nabetani/asciidoctor-nabetani
Diagram::
    * PlantUML - Multi(MIT/Apache/BSD/EPL/GPLv3/LGPL) - https://github.com/plantuml/plantuml
    * ditaa - LGPL-3.0 license - https://github.com/stathissideris/ditaa
Build Tool::
    * SDKMAN - Apache License 2.0 - https://sdkman.io/
    * Gradle - Apache License 2.0 - https://gradle.org/
Text Editor::
    * Visual Studio Code - Microsoft - https://code.visualstudio.com/
    * asciidoctor-vscode - MIT License - https://github.com/asciidoctor/asciidoctor-vscode
    * vscode-paste-image - MIT License - https://github.com/mushanshitiancai/vscode-paste-image
    * vscode-plantuml - MIT License - https://github.com/qjebbs/vscode-plantuml
    * Code Spell Checker - GPL - https://github.com/streetsidesoftware/vscode-spell-checker
Guide::
    * asciidoctor-pdfでかっこいいPDFを作る - https://qiita.com/kuboaki/items/67774c5ebd41467b83e2

素晴らしい成果を公開されているみなさまに感謝します。
