@startuml diag-timing-sample1
<style>
timingDiagram {
    LineColor gray
    FontSize 14
}
</style>
'mode compact
scale 40 as 150 pixels
clock "Clock" as clk with period 1
binary "CS" as CS
binary "WR" as WR
binary "RD" as RD
binary "A0" as A0
binary "A1" as A1
binary "IC" as IC
concise "DataBus" as DB

@0 as :start
@20 as :set_data_bus_1
@30 as :set_addr_1
@40 as :write_start_1
@60 as :write_end_1
@80 as :set_data_bus_2
@90 as :set_addr_2
@100 as :write_start_2
@120 as :write_end_2

@:start
IC is high
CS is high
WR is high
RD is low
A0 is low
A1 is low

@:set_data_bus_1
DB is "0xff"
DB -> WR@+20

@:set_addr_1
A0 is high
A1 is low

@:write_start_1
CS is low : WR/CS 同時に設定
WR is low
DB@40 <-> @60 : {10 us}

@:write_end_1
CS is high
WR is high

@:set_data_bus_2
DB is "0x01"
DB -> WR@+20

@:set_addr_2
A0 is low
A1 is high

@:write_start_2
CS is low
WR is low

@:write_end_2
CS is high
WR is high

highlight 40 to 60 #SkyBlue;line:DimGrey : 書き込み
highlight 100 to 120 #SkyBlue;line:DimGrey : 書き込み
@enduml
