== ダイアグラム記法

本変換スクリプトでは `asciidoctorj-diagram` が有効になっており、いくつかのダイアグラム記法を追加のアドイン無しで使うことができます。

ダイアグラムを SVG ベクター画像で出力する指定は次のようになります。

[source]
-----
[ダイアグラム名, 出力ファイル名, svg, pdfwidth=70%, width=480px]
-----

``pdfwidth`` は PDF 紙面に対しての比率指定、``width`` は HTML 上の幅比率もしくはピクセル（``px``）で指定します。

本章では PlantUML と ditaa ダイアグラム記法を用いて、技術文書で使われやすい表現のいくつかの記述法を示します。詳しくはそれぞれのドキュメントを参考にしてください。

[quote, PlantUML]
____
https://plantuml.com/ja/

PlantUML in a nutshell
____

TIP: 変換スクリプトは PlantUML ダイアグラムの PDF 出力時に日本語が化けないよう、自動的にフォントパッチが適用されるよう構成されています。

[quote, ditaa]
____
https://ditaa.sourceforge.net/

DIagrams Through Ascii Art by Stathis Sideris
____

<<<<

=== シーケンス図

シーケンス図を PlantUML ダイアグラム記法で記述します。

[source]
-----
[plantuml, diag-sequence-sample2, svg, pdfwidth=70%, width=70%]
[caption=""]
----
include::puml/diag-sequence-sample2.puml[]
----
-----

[plantuml, diag-sequence-sample2, svg, pdfwidth=70%, width=70%]
[caption=""]
----
include::puml/diag-sequence-sample2.puml[]
----

.PlantUML ダイアグラムのリアルタイムプレビュー編集
****
本手順の VS Code の推奨プラグインとなっている PlantUML 拡張（``jebbs.plantuml``）を使うと、PlantUML のダイアグラム記法も VS Code 上でリアルタイムプレビューすることができます。

プレビュー処理をするために必要な PlantUML サーバは Docker コンテナで起動すると便利でしょう。なお、Gradle による文書の変換では内蔵の PlantUML ライブラリが使われますので本サーバーが起動している必要はありません。

[source, bash]
----
docker run -d --rm -p 8080:8080 plantuml/plantuml-server:jetty
----

`.vscode/setting.json` は次のようにポート ``8080`` で PlantUML サーバが起動されることを期待して構成してあります。

[source, json]
[caption=""]
.`.vscode/setting.json`
----
{ "plantuml.server": "http://localhost:8080" }
----

文書で使う PlantUML ダイアグラムを `.puml` 拡張子で保存することで Asciidoc と同様にプレビューアイコンが表示され、プレビュー画面ではリアルタイムに `.puml` ファイルの修正が反映されます。
****

<<<<

=== フォルダ・ファイルツリー

フォルダ・ファイルツリーを PlantUML の Salt 記法で記述します。

[source]
-----
[plantuml, diag-salt-sample1, svg, pdfwidth=30%, width=280px]
[caption=""]
----
include::puml/diag-salt-sample1.puml[]
----
-----

[plantuml, diag-salt-sample1, svg, pdfwidth=30%, width=280px]
[caption=""]
----
include::puml/diag-salt-sample1.puml[]
----

<<<<

=== 数式

数式を PlantUML の AsciiMath 記法で記述します。

[source]
-----
[plantuml, math-sample1, svg, pdfwidth=70%, width=70%]
[caption=""]
----
include::puml/math-sample1.puml[]
----
-----

[plantuml, math-sample1, svg, pdfwidth=70%, width=70%]
[caption=""]
----
include::puml/math-sample1.puml[]
----

- - -

.PlantUML の Salt 記法のフォントサイズ
****
Salt は現在のところ残念ながらフォントサイズの指定をすることができません。このため任意のフォントサイズにするためには出力画像の ``pdfwidth`` と ``width`` を設定して算出する必要があります。

[source]
----
@startsalt
<style>
saltDiagram {
  FontSize 10 // <1>
}
</style>
{
{T
 + <&folder> wp-admin
}
}
@endsalt
----

<1> 未実装で効果がない
****

<<<<

=== ブロック図

ブロック図を ditaa 記法で記述します。

TIP: ditta 内で日本語を使う場合は、表示ずれを防ぐため半角スペースなどで文字数を調整する必要があります。また、ドロップシャドー ``shadows`` 設定は HTML 版に対してのみ有効で PDF 版に対しては効果がないようです。

[source]
-----
[ditaa, diag-ditaa-block, svg, shadows=true, separation=true, pdfwidth=70%, width=70%]
[caption=""]
----
+---------------------------------+
|     baserCMS Plugin, Theme      |
+----------------------------+    +
| cPNK   baserCMS Core       |    |
+----------------------------+----+
|            CakePHP              |
+---------------------------------+
|             MySQL               |
+---------------------------------+

/-------------+-------------\
|cRED RED     |cBLU BLU     |
+-------------+-------------+
|cGRE GRE     |cPNK PNK     |
+-------------+-------------+
|cBLK BLK     |cYEL YEL     |
\-------------+-------------/
----
-----

[ditaa, diag-ditaa-block, svg, shadows=true, separation=true, pdfwidth=70%, width=70%]
[caption=""]
----
+---------------------------------+
|     baserCMS Plugin, Theme      |
+----------------------------+    +
| cPNK   baserCMS Core       |    |
+----------------------------+----+
|            CakePHP              |
+---------------------------------+
|             MySQL               |
+---------------------------------+

/-------------+-------------\
|cRED RED     |cBLU BLU     |
+-------------+-------------+
|cGRE GRE     |cPNK PNK     |
+-------------+-------------+
|cBLK BLK     |cYEL YEL     |
\-------------+-------------/
----
