== ダイアグラム記法

本変換スクリプトでは `asciidoctorj-diagram` が有効になっており、いくつかのダイアグラム記法を追加のアドイン無しで使うことができます。

ダイアグラムを SVG ベクター画像で出力する指定は次のようになります。

[source]
-----
[ダイアグラム名, 出力ファイル名, svg, pdfwidth=70%, width=480px]
-----

``pdfwidth`` は PDF 紙面に対しての比率指定、``width`` は HTML 上の幅比率もしくはピクセル（``px``）で指定します。

本章では PlantUML と ditaa ダイアグラム記法を用いて、技術文書で使われやすい表現のいくつかの記述法を示します。詳しくはそれぞれのドキュメントを参考にしてください。

[quote, PlantUML]
____
https://plantuml.com/ja/

PlantUML in a nutshell
____

TIP: 変換スクリプトは PlantUML ダイアグラムの PDF 出力時に日本語が化けないよう、自動的にフォントパッチが適用されるよう構成されています。

[quote, ditaa]
____
https://ditaa.sourceforge.net/

DIagrams Through Ascii Art by Stathis Sideris
____

<<<<

=== シーケンス図

シーケンス図を PlantUML ダイアグラム記法で記述します。

[source]
-----
[plantuml, diag-sequence-sample2, svg, pdfwidth=70%, width=70%]
[caption=""]
----
include::puml/diag-sequence-sample2.puml[]
----
-----

[plantuml, diag-sequence-sample2, svg, pdfwidth=70%, width=70%]
[caption=""]
----
include::puml/diag-sequence-sample2.puml[]
----

.PlantUML ダイアグラムのリアルタイムプレビュー編集
****
本手順の VS Code の推奨プラグインとなっている PlantUML 拡張（``jebbs.plantuml``）を使うと、PlantUML のダイアグラム記法も VS Code 上でリアルタイムプレビューすることができます。

プレビュー処理をするために必要な PlantUML サーバは Docker コンテナで起動すると便利でしょう。なお、Gradle による文書の変換では内蔵の PlantUML ライブラリが使われますので本サーバーが起動している必要はありません。

[source, bash]
----
docker run -d --rm -p 8080:8080 plantuml/plantuml-server:jetty
----

`.vscode/setting.json` は次のようにポート ``8080`` で PlantUML サーバが起動されることを期待して構成してあります。

[source, json]
[caption=""]
.`.vscode/setting.json`
----
{ "plantuml.server": "http://localhost:8080" }
----

文書で使う PlantUML ダイアグラムを `.puml` 拡張子で保存することで Asciidoc と同様にプレビューアイコンが表示され、プレビュー画面ではリアルタイムに `.puml` ファイルの修正が反映されます。
****

<<<<

=== フォルダ・ファイルツリー

フォルダ・ファイルツリーを PlantUML の Salt 記法で記述します。

[source]
-----
[plantuml, diag-salt-sample1, svg, pdfwidth=30%, width=280px]
[caption=""]
----
include::puml/diag-salt-sample1.puml[]
----
-----

[plantuml, diag-salt-sample1, svg, pdfwidth=30%, width=280px]
[caption=""]
----
include::puml/diag-salt-sample1.puml[]
----

<<<<

=== 数式

数式を PlantUML の AsciiMath 記法で記述します。

[source]
-----
[plantuml, math-sample1, svg, pdfwidth=70%, width=70%]
[caption=""]
----
include::puml/math-sample1.puml[]
----
-----

[plantuml, math-sample1, svg, pdfwidth=70%, width=70%]
[caption=""]
----
include::puml/math-sample1.puml[]
----

- - -

.PlantUML の Salt 記法のフォントサイズ
****
Salt は現在のところ残念ながらフォントサイズの指定をすることができません。このため任意のフォントサイズにするためには出力画像の ``pdfwidth`` と ``width`` を設定して算出する必要があります。

[source]
----
@startsalt
<style>
saltDiagram {
  FontSize 10 // <1>
}
</style>
{
{T
 + <&folder> wp-admin
}
}
@endsalt
----

<1> 未実装で効果がない
****

<<<<

=== ブロック図

ブロック図を ditaa 記法で記述します。

TIP: ditta 内で日本語を使う場合は、表示ずれを防ぐため半角スペースなどで文字数を調整する必要があります。また、ドロップシャドー ``shadows`` 設定は HTML 版に対してのみ有効で、現在のところ PDF 版に対しては効果がないようです。

[source]
-----
[ditaa, diag-ditaa-block, svg, shadows=true, separation=true, pdfwidth=70%, width=70%]
[caption=""]
----
+---------------------------------+
|     baserCMS Plugin, Theme      |
+----------------------------+    +
| cPNK   baserCMS Core       |    |
+----------------------------+----+
|            CakePHP              |
+---------------------------------+
|             MySQL               |
+---------------------------------+

/-------------+-------------\
|cRED RED     |cBLU BLU     |
+-------------+-------------+
|cGRE GRE     |cPNK PNK     |
+-------------+-------------+
|cBLK BLK     |cYEL YEL     |
\-------------+-------------/
----
-----

[ditaa, diag-ditaa-block, svg, shadows=true, separation=true, pdfwidth=70%, width=70%]
[caption=""]
----
+---------------------------------+
|     baserCMS Plugin, Theme      |
+----------------------------+    +
| cPNK   baserCMS Core       |    |
+----------------------------+----+
|            CakePHP              |
+---------------------------------+
|             MySQL               |
+---------------------------------+

/-------------+-------------\
|cRED RED     |cBLU BLU     |
+-------------+-------------+
|cGRE GRE     |cPNK PNK     |
+-------------+-------------+
|cBLK BLK     |cYEL YEL     |
\-------------+-------------/
----

<<<<

=== ネットワーク構成図

ネットワーク構成図を PlantUML の nwdiag で記述します。

[source]
[caption=""]
.``diag-nwdiag-network1.puml``（分かりやすいように実際のソースより簡略化）
-----
[plantuml, diag-nwdiag-network1, svg]
----
@startuml diag-network1
<style>
nwdiagDiagram {
    FontSize 14
    group {
        BackGroundColor cadetblue
    }
}
</style>

nwdiag {
    internet [shape = cloud];
    internet -- router;
    router [address = "210.x.x.x"];
    network LAN {
        address = "192.168.0.0/24"
        router [address = "192.168.0.1"];
        thinkpad-p14s [address = "192.168.0.w"];
        minis-um690 [address = "192.168.0.x"];
        xbox-series-s [address = "192.168.0.y"];
        atom-server [address = "192.168.0.z", shape = database"]
    }
    network WLAN {
        address = "172.16.15.0/24"
        router [address = "172.16.15.1"];
        group {
            description = モバイル
            iphone01 [address = "172.16.15.w"];
            ipad01 [address = "172.16.15.x"];
        }
        group {
            color = "#add8e6"
            description = 据え置き
            fire01 [address = "172.16.15.y"];
            echo01 [address = "172.16.15.z"];
        }
    }
}
@enduml
----
-----

[plantuml, diag-nwdiag-network1, svg, pdfwidth=95%]
[caption=""]
----
include::puml/diag-nwdiag-network1.puml[]
----

.WSL2 上の VS Code で Paste Image 拡張を使う
****
本手順は Windows WSL2 上の Linux と VS Code の WSL Remote 拡張でも構成できますが、VS Code Paste Image 拡張はそのままでは OS のクリップボードを跨げないためうまく動作しません。

これを解決するために、ワークアラウンドですが次のように拡張のファイルを書き換えると動作するようになります。Asciidoc 拡張も同じ方法で修正できます。なお、拡張にアップデートがあるとファイルが戻りますので注意してください。

[source, bash]
[caption=""]
.``~/.vscode-server/extensions/mushan.vscode-paste-image-1.0.4/res/linux.sh``
----
#!/bin/sh
# change current directoru
cd `dirname $0`
# set dist path
DISTPATH=//wsl.localhost/Ubuntu-22.04 # <1>
# call Windows PowerShell
powershell.exe -ExecutionPolicy Bypass -File pc.ps1 ${DISTPATH}$1
----

<1> 利用しているディストリビューションのパスを設定する。
****

<<<<

=== システム構成図

簡単なシステム構成図を PlantUML/C4 コンポーネントで記述します。

[source]
-----
[plantuml, diag-c4-component-sample1, svg]
[caption=""]
----
include::puml/diag-c4-component-sample1.puml[]
----
-----

[plantuml, diag-c4-component-sample1, svg]
[caption=""]
----
include::puml/diag-c4-component-sample1.puml[]
----

TIP: 現在のところ ``$shadowing="true"`` 指定のドロップシャドーは HTML 版のみ反映します。

<<<<

=== タイミングチャート

デジタル回路などのタイミングチャートを PlantUML で記述します。

[source]
[caption=""]
.``diag-timing-sample1.puml``（実際のソースより抜粋）
-----
[plantuml, diag-timing-sample1, svg, pdfwidth=90%, width=80%]
----
@startuml diag-timing-sample1
scale 40 as 150 pixels
clock "Clock" as clk with period 1
binary "CS" as CS
binary "WR" as WR
binary "RD" as RD
binary "A0" as A0
binary "A1" as A1
binary "IC" as IC
concise "DataBus" as DB

@0 as :start
@20 as :set_data_bus_1
@30 as :set_addr_1
@40 as :write_start_1
@60 as :write_end_1

@:start
IC is high
CS is high
WR is high
RD is low
A0 is low
A1 is low

@:set_data_bus_1
DB is "0xff"
DB -> WR@+20

@:set_addr_1
A0 is high
A1 is low

@:write_start_1
CS is low : WR/CS と同時に設定
WR is low

@:write_end_1
CS is high
WR is high

highlight 40 to 60 #Gold;line:DimGrey : 書き込み
@enduml
----
-----

[plantuml, diag-timing-sample1, svg, pdfwidth=90%, width=80%]
[caption=""]
----
include::puml/diag-timing-sample1.puml[]
----

- - -

.Open Iconic アイコン
****
PlantUML 内で ``<&アイコン名>`` 形式で使える Open Iconic アイコンは次の通りです。アイコン名は HTML 版の場合 menu:ウェブブラウザ[右クリック > 画像を開く] するとコピーアンドペーストで取得できます。

[plantuml, open-iconic-list, svg]
[caption=""]
----
@startuml
listopeniconic
@enduml
----
****

<<<<

=== マインドマップ

PlantUML のマインドマップ記法を使い木構造を表現します。

[source]
-----
[plantuml, diag-mindmap-sample1, svg]
[caption=""]
----
include::puml/diag-mindmap-sample1.puml[]
----
-----

[plantuml, diag-mindmap-sample1, svg]
[caption=""]
----
include::puml/diag-mindmap-sample1.puml[]
----
