name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-22.04

    strategy:
      matrix:
        java: [ '11', '17' ]

    name: Java ${{ matrix.Java }} build test

    steps:
    - uses: actions/checkout@v1

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}

    - name: Build with Gradle
      run: ./gradlew docs

    - name: Check
      run: |
        find docs/ -type f -ls
        find docs/ -type f -ls | wc
        # test asciidoctor-diagram
        find docs/ -type f -ls | egrep 'svg$'
        # test asciidoctor
        file docs/index.pdf | grep PDF
        file docs/index.html | grep HTML
