name: Java CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-22.04, windows-latest ]
        java: [ '11', '17' ]

    runs-on: ${{ matrix.os }}

    name: ${{ matrix.os }} - Java ${{ matrix.java }} build test

    steps:
    - uses: actions/checkout@v1

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}

    - name: Build with Gradle
      run: ./gradlew docs

    - name: Check (Linux)
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        find docs/ -type f -ls
        find docs/ -type f -ls | wc
        # test asciidoctor-diagram
        find docs/ -type f -ls | egrep 'svg$'
        # test asciidoctor
        file docs/index.pdf | grep PDF
        file docs/index.html | grep HTML

    - name: Check (Windows)
      if: startsWith(matrix.os, 'windows')
      shell: pwsh
      run: |
        Get-ChildItem -Recurse -File -Name docs
        $(Get-ChildItem -Recurse -File docs).Length
        Get-ChildItem -Recurse -File -Name -Filter "*.svg" docs
        (Get-ChildItem -Recurse -File -Name -Filter "*.svg" docs).Length -ne 0
        # test asciidoctor
        Get-ChildItem docs/index.pdf
        Get-ChildItem docs/index.html
