name: Release

on:
  push:
    tags:
    - '*'

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: [ windows-latest, macos-latest ]
        java: [ '11', '17' ]

    runs-on: ${{ matrix.os }}

    name: ${{ matrix.os }} - Java ${{ matrix.java }} release

    steps:
      - uses: actions/checkout@v1

      - name: Setup Environment (Ubuntu)
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt update
          sudo apt upgrade
          sudo apt install language-pack-ja-base language-pack-ja
          sudo update-locale LANG=ja_JP.UTF8
          sudo apt install fonts-noto* language-selector-common
          export LANG=ja_JP.UTF-8
          fc-cache -f
          fc-match sans-serif | grep NotoSansCJK
          sudo apt install graphviz
          # for GitHub Actions test
          sudo apt install poppler-utils

      - name: Setup Environment (macOS)
        if: startsWith(matrix.os, 'macos')
        run: |
          brew install graphviz

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}

      - name: Build with Gradle (Ubuntu)
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          export LANG=ja_JP.UTF-8
          fc-match sans-serif | grep NotoSansCJK
          ./gradlew docs

      - name: Build with Gradle (macOS)
        if: startsWith(matrix.os, 'macos')
        run: |
          ./gradlew docs

      - name: Build with Gradle (Windows)
        if: startsWith(matrix.os, 'windows')
        run: |
          .\gradlew docs

      - name: Arcive
        run: tar zcvf release-by-${{ matrix.os }}-java-${{ matrix.java }}.tar.gz docs

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "release-by-${{ matrix.os }}-java-${{ matrix.java }}.tar.gz"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
